# Generated by Django 5.2.17 on 2026-10-06 18:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClientPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_scopes', models.JSONField(blank=True, default=None, help_text='Scopes used when the client omits scope. Empty means use global defaults.', null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_policy', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth client defaults',
                'verbose_name_plural': 'OAuth client defaults',
            },
        ),
        migrations.CreateModel(
            name='OAuthResourcePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uri', models.URLField(help_text="Canonical HTTPS URI used as this resource's audience.", max_length=500, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Scopes this client may request for this resource.')),
                ('is_default', models.BooleanField(default=False, help_text='Use this audience when the client does not send a resource parameter.')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_policies', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth resource policy',
                'verbose_name_plural': 'OAuth resource policies',
                'ordering': ('application__client_id', 'resource_uri'),
                'constraints': [models.UniqueConstraint(fields=('application', 'resource_uri'), name='oauth_resource_policy_unique_resource'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('application',), name='oauth_resource_policy_one_default')],
            },
        ),
    ]
