# Generated by Django 5.2.17 on 2026-10-06 18:42

import oauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthresourcepolicy',
            name='resource_uri',
            field=models.URLField(help_text="Canonical HTTPS URI used as this resource's audience.", max_length=500, validators=[oauth.models.validate_resource_uri]),
        ),
    ]
