"""
Django settings for pyauthservice project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import environ
import certifi
import os
import logging

logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loading environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'gunicorn.error': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'gunicorn.access': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

def _merge_env_list(defaults, setting_name):
    return list(dict.fromkeys(defaults + env.list(setting_name, default=[])))


ALLOWED_HOSTS = _merge_env_list([
    'localhost',
    '127.0.0.1',
], 'ALLOWED_HOSTS')

CSRF_TRUSTED_ORIGINS = _merge_env_list([
    "http://localhost:3000",
    "http://127.0.0.1:3000",
], 'CSRF_TRUSTED_ORIGINS')

# CORS settings
CORS_ALLOWED_ORIGINS = _merge_env_list([
    "http://localhost:3000",
    "http://127.0.0.1:3000",
], 'CORS_ALLOWED_ORIGINS')

CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'oauth2_provider',
    'oauth',
    'rest_framework',
    'corsheaders',
    'virtual_permissions',
    'axes',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'pyauthservice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'pyauthservice', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pyauthservice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DB_ENGINE = env('DB_ENGINE', default='sqlite3' if DEBUG else 'postgresql')
DB_CONN_MAX_AGE = env.int('DB_CONN_MAX_AGE', default=0 if DEBUG else 60)
POSTGRES_SSLMODE = env('POSTGRES_SSLMODE', default='disable')

if DB_ENGINE == 'sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db' / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('POSTGRES_DB', default='hacksaw'),
            'USER': env('POSTGRES_USER', default='authuser'),
            'PASSWORD': env('POSTGRES_PASSWORD', default='authpassword'),
            'HOST': env('POSTGRES_HOST', default='db'),
            'PORT': env('POSTGRES_PORT', default='5432'),
            'CONN_MAX_AGE': DB_CONN_MAX_AGE,
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                'sslmode': POSTGRES_SSLMODE,
            },
        },
    }

    if POSTGRES_SSLMODE == 'verify-full':
        DATABASES['default']['OPTIONS']['sslrootcert'] = certifi.where()

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'axes.backends.AxesStandaloneBackend',
]

AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'

OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 3600 * 24 * 365,
    'PKCE_REQUIRED': env.bool('OAUTH2_PKCE_REQUIRED', default=False),
    "ACCESS_TOKEN_GENERATOR": "oauth.jwt_tokens.jwt_access_token_generator",
    "REFRESH_TOKEN_GENERATOR": "oauth.jwt_tokens.opaque_refresh_token_generator",
    'OIDC_ENABLED': True,
    'OAUTH2_VALIDATOR_CLASS': 'oauth.validators.UserClaimsValidator',
    # OIDC RSA private key: prefer raw key in env, then a path in env, then BASE_DIR/oidc_private.pem
    # Set either `OIDC_RSA_PRIVATE_KEY` (PEM content) or `OIDC_PRIVATE_KEY_PATH` (path to PEM file)
    # or place `oidc_private.pem` at the project root.
    'OIDC_RSA_PRIVATE_KEY': None,
    'OIDC_ISS_ENDPOINT': env('OIDC_ISS_ENDPOINT'),
    'SCOPES': {
        "read": "Read-only access",
        "write": "Write access",
        "openid": "OpenID Connect scope",
        "email": "Access to the user's email address",
        "profile": "Access to the user's profile information",
    },
}

# Resolve OIDC private key (populate the dict value above)
OIDC_RSA_PRIVATE_KEY = env('OIDC_RSA_PRIVATE_KEY', default=None)
OIDC_PRIVATE_KEY_PATH = env('OIDC_PRIVATE_KEY_PATH', default=None)

if OIDC_RSA_PRIVATE_KEY:
    # If OIDC_RSA_PRIVATE_KEY is set, reconstruct it from inline format
    # (newlines are escaped as literal \n in env vars)
    if '\\n' in OIDC_RSA_PRIVATE_KEY and '\n' not in OIDC_RSA_PRIVATE_KEY:
        OIDC_RSA_PRIVATE_KEY = OIDC_RSA_PRIVATE_KEY.replace('\\n', '\n')
elif OIDC_PRIVATE_KEY_PATH:
    try:
        OIDC_RSA_PRIVATE_KEY = Path(OIDC_PRIVATE_KEY_PATH).read_text()
    except Exception as e:
        logger.error(f"Failed to read OIDC key from {OIDC_PRIVATE_KEY_PATH}: {e}")
        OIDC_RSA_PRIVATE_KEY = None

if not OIDC_RSA_PRIVATE_KEY:
    pem_path = BASE_DIR / 'oidc_private.pem'
    if pem_path.exists():
        OIDC_RSA_PRIVATE_KEY = pem_path.read_text()

if not OIDC_RSA_PRIVATE_KEY:
    raise RuntimeError(
        "OIDC private key not found. Set OIDC_RSA_PRIVATE_KEY (inline PEM with \\n), "
        "or OIDC_PRIVATE_KEY_PATH (path to PEM), or add oidc_private.pem at project root."
    )

# Inject back into provider config
OAUTH2_PROVIDER['OIDC_RSA_PRIVATE_KEY'] = OIDC_RSA_PRIVATE_KEY

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "oauth.authentication.SSOJWTAuthentication",
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
    ],
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = env('STATIC_URL', default='/static/')
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

# AXES rate-limit / brute-force guard (session auth only)
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hour
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = 'users/login.html'

LOGIN_THEME_COLOR = env('LOGIN_THEME_COLOR', default='#4f46e5')
LOGIN_LOGO_URL = env('LOGIN_LOGO_URL', default='')
LOGIN_PAGE_TITLE = env('LOGIN_PAGE_TITLE', default='Login | Auth Service')

SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
