name: Deploy Image to EC2

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: Image tag to deploy
        required: true
        default: latest

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    uses: hacksawrazor/ci-cd/.github/workflows/deploy-docker-oci-existing.yml@main
    with:
      image-name: '${{ github.repository }}'
      image-tag: ${{ inputs.image-tag }}
      deploy-path: '/opt/apps/auth'
      use-sudo: true
    secrets:
      SSH_HOST: ${{ secrets.SERVER_HOST_EC2 }}
      SSH_USER: ${{ secrets.SERVER_USER_EC2 }}
      SSH_KEY: ${{ secrets.SERVER_SSH_KEY_EC2 }}
      INDIVIDUAL_SECRETS_JSON: ${{ toJson(vars) }}