name: Deploy Application - EC2

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  deploy:
    env:
      SECRET_KEY: dummy-test-secret-key
      OIDC_ISS_ENDPOINT: https://auth.hacksaw.in
      OIDC_PRIVATE_KEY_PATH: /tmp/oidc_test_key.pem
    uses: hacksawrazor/ci-cd/.github/workflows/deploy-docker-ghcr.yml@main
    with:
      aws-region: 'eu-north-1'
      aws-role-to-assume: 'arn:aws:iam::286123980000:role/GithubActionsAccess'
      image-name: '${{ github.repository }}'
      deploy-path: '/opt/apps/auth'
      container-port: '8000:8000'
      use-sudo: true
    secrets:
      SSH_HOST: ${{ secrets.SERVER_HOST_EC2 }}
      SSH_USER: ${{ secrets.SERVER_USER_EC2 }}
      SSH_KEY: ${{ secrets.SERVER_SSH_KEY_EC2 }}
      
      # Maps all individual repository secrets dynamically into .env generator
      INDIVIDUAL_SECRETS_JSON: ${{ toJson(vars) }}
