name: Deploy Application - OCI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: hacksawrazor/ci-cd/.github/workflows/deploy-docker-oci.yml@main
    with:
      image-name: '${{ github.repository }}'
      deploy-path: '/opt/apps/auth'
      use-sudo: true
    secrets:
      SSH_HOST: ${{ secrets.SERVER_HOST_OCI }}
      SSH_USER: ${{ secrets.SERVER_USER_OCI }}
      SSH_KEY: ${{ secrets.SERVER_SSH_KEY_OCI }}
      INDIVIDUAL_SECRETS_JSON: ${{ toJson(vars) }}
