name: Build & Deploy Application - OCI

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    env:
      SECRET_KEY: dummy-test-secret-key
      OIDC_ISS_ENDPOINT: https://auth.hacksaw.in
      OIDC_PRIVATE_KEY_PATH: /tmp/oidc_test_key.pem
    uses: hacksawrazor/ci-cd/.github/workflows/deploy-docker-oci.yml@main
    with:
      image-name: '${{ github.repository }}'
      deploy-path: '/opt/apps/auth'
      use-sudo: true
    secrets:
      SSH_HOST: ${{ secrets.SERVER_HOST_OCI }}
      SSH_USER: ${{ secrets.SERVER_USER_OCI }}
      SSH_KEY: ${{ secrets.SERVER_SSH_KEY_OCI }}
      INDIVIDUAL_SECRETS_JSON: ${{ toJson(vars) }}
